#!/bin/bash

DNS_SERVICE_IP=$(terraform output dns-service-ip)

cat <<EOF | kubectl create -f -
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${PERSISTENT_VOLUME}
    path: "/"
EOF